### PR TITLE
Add a google maps navigation URL

### PR DESCRIPTION
**Pull request by xkjyeah**
I was taking a Beeline, and the driver got lost. :(

### CODE REVIEW

**Comment by xkjyeah** [comment]
image

Note: Only waypoints with pickup/dropoff activity are included for navigation. This may have implications if the driver turns on the app too early (before the booking cut-off)

**Comment by xkjyeah** [comment]
Or is the button at the bottom better?
image

**Comment by chuasweechin** [comment]
Can consider putting the icon at top left corner.

Most driver turn on the app 25 mins before trip start so the way point
might not be accurate. Unless what we do is we will block the button until
the booking is closed.

**Comment by xkjyeah** [comment]
Like so? (button will be enabled once booking window is closed)

image

**Comment by chuasweechin** [comment]
Yeah, once booking window close.

**Comment by chuasweechin** [comment]
Possible to grey off the whole google map icon to make it less enabled?

**Comment by xkjyeah** [comment]
I already reduced opacity. Will have more vibrant colours when it's enabled

**Comment by chuasweechin** [comment]
As in make the vibrate color even less vibrate. Downplay it abit more if
possible

**Comment by xkjyeah** [comment]
image

**Comment by chuasweechin** [comment]
Can make it till this color state?

**Comment by xkjyeah** [comment]
What do you mean by till colour state?

**Comment by xkjyeah** [comment]
Ooops sorry can't see your attachment. Send over chat?

**Comment by xkjyeah** [comment]
`
image

**Comment by xkjyeah** [comment]
image

i've fully desaturated the image.... any color left and it's really down to our imagination

**Comment by chuasweechin** [comment]
Haha looks good. But i can feel u feel sad about losing colors in life haha

**Comment by xkjyeah** [comment]
Lol I just can't see too much difference between this and the previous

**Comment by xkjyeah** [comment]
image

**Comment by xkjyeah** [comment]
For the record: for now, if the user switches to the Driving navigation app, the Beeline driver app will stop receiving notification updates. (But that's still better than the driver getting lost)

Can't fix this without an extra service.

**Comment by LoneRifle** [comment]
what will we do with this?

**Comment by joelchoo** [comment]
There was some discussion with @chuasweechin but I don't remember how it was resolved

**Comment by LoneRifle** [comment]
Seems like it's already been published. Unless anybody objects, I'll merge this into master

**Pull request merged**
